import { Candle, ConnectorType, MarketType, TimeFrame } from '@barfinex/types';

const INTERVAL_MS: Partial<Record<TimeFrame, number>> = {
  [TimeFrame.min1]: 60_000,
  [TimeFrame.min5]: 300_000,
  [TimeFrame.min15]: 900_000,
  [TimeFrame.min30]: 1_800_000,
  [TimeFrame.h1]: 3_600_000,
  [TimeFrame.h2]: 7_200_000,
  [TimeFrame.h4]: 14_400_000,
  [TimeFrame.day]: 86_400_000,
};

/**
 * Box–Muller transform: generates a standard normal random variable.
 */
function normalRandom(): number {
  let u = 0;
  let v = 0;
  while (u === 0) u = Math.random();
  while (v === 0) v = Math.random();
  return Math.sqrt(-2.0 * Math.log(u)) * Math.cos(2.0 * Math.PI * v);
}

export interface GenerateSyntheticCandlesParams {
  symbol: string;
  interval: TimeFrame;
  numCandles: number;
  startPrice: number;
  /** Per-candle log-normal sigma (0.015 = ~1.5% per bar). */
  volatility: number;
  /** Per-candle log drift. 0 = pure random walk. */
  trend: number;
  connectorType: ConnectorType;
  marketType: MarketType;
}

/**
 * Generates synthetic OHLCV candles using Geometric Brownian Motion.
 * Each candle's close is sampled from: prev_close × exp((drift - σ²/2) + σ × Z).
 * High/Low are generated by adding intra-bar noise proportional to σ.
 * Volume scales with absolute return magnitude.
 */
export function generateSyntheticCandles(
  params: GenerateSyntheticCandlesParams,
): Candle[] {
  const intervalMs = INTERVAL_MS[params.interval] ?? 60_000;
  // End at current time so candles look "recent"
  const endTime = Date.now();
  const startTime = endTime - params.numCandles * intervalMs;

  const candles: Candle[] = [];
  let price = params.startPrice;

  for (let i = 0; i < params.numCandles; i++) {
    const open = price;

    // GBM step: close = open × exp((μ - σ²/2) + σ × Z)
    const z = normalRandom();
    const logReturn =
      params.trend - params.volatility ** 2 / 2 + params.volatility * z;
    const close = Math.max(0.01, open * Math.exp(logReturn));

    // Intra-bar noise for high/low (always positive fraction of range)
    const intrabarNoise =
      Math.abs(normalRandom()) * params.volatility * open * 0.4;
    const high = Math.max(open, close) + intrabarNoise;
    const low = Math.max(0.01, Math.min(open, close) - intrabarNoise);

    // Volume: higher when move is large
    const absReturn = Math.abs(logReturn);
    const baseVolume = 80 + Math.random() * 40;
    const volume = baseVolume * (1 + absReturn * 20);

    const candleTime = startTime + (i + 1) * intervalMs;

    candles.push({
      open,
      close,
      high,
      low,
      volume,
      time: candleTime,
      interval: params.interval,
      instrument: { symbol: params.symbol },
    });

    price = close;
  }

  return candles;
}
